
<div style="<?=($this->form_data['debug_form']) ? "display: table;" : "display: none;" ?>">

    <?php if($this->form_data['debug_form']): ?>
    <p><b>Message to hash</b>: <?=$this->message_to_hash?></p>
    <p><b>Hash</b>: <?=$this->hash?></p>
    <?php endif; ?>

    <form action="<?= $this->form_data['post_url'] ?>" id="s2pform" method="POST" <?php if($this->form_data['redirect_in_iframe']) echo 'target="merchantIframe"'; ?>>
        <table>
            <tr>
                <td>
                    MerchantID
                </td>
                <td>
                    <input type="text" name="MerchantID" value="<?= $this->form_data['mid'] ?>"/>
                </td>
            </tr>
            <tr>
                <td>
                    MerchantTransactionID
                </td>
                <td>
                    <input type="text" name="MerchantTransactionID" value="<?= $this->form_data['order_id'] ?>"/>
                </td>
            </tr>
            <tr>
                <td>
                    Amount
                </td>
                <td>
                    <input type="text" name="Amount" value="<?= $this->form_data['amount'] ?>"/>
                </td>
            </tr>
            <tr>
                <td>
                    Currency
                </td>
                <td>
                    <input type="text" name="Currency" value="<?= $this->form_data['currency'] ?>"/>
                </td>
            </tr>
            <tr>
                <td>
                    ReturnURL
                </td>
                <td>
                    <input type="text" name="ReturnURL" value="<?= $this->form_data['return_url'] ?>"/>
                </td>
            </tr>
            <tr>
                <td>
                    IncludeMethodIDs
                </td>
                <td>
                    <input type="text" name="IncludeMethodIDs" value="<?= $this->form_data['methods'] ?>"/>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Optional:
                </td>
            </tr>
            <?php if($this->form_data['send_customer_name']): ?>
            <tr>
                <td>
                    CustomerName
                </td>
                <td>
                    <input type="text" name="CustomerName" value="<?= $this->form_data['customer_name'] ?>"/>
                </td>
            </tr>
            <?php endif; ?>

            <?php if($this->form_data['send_customer_email']): ?>
            <tr>
                <td>
                    CustomerEmail
                </td>
                <td>
                    <input type="text" name="CustomerEmail" value="<?= $this->form_data['customer_email'] ?>"/>
                </td>
            </tr>
            <?php endif; ?>

            <?php if($this->form_data['send_country']): ?>
            <tr>
                <td>
                    Country
                </td>
                <td>
                    <input type="text" name="Country" value="<?= $this->form_data['country'] ?>"/>
                </td>
            </tr>
            <?php endif; ?>

            <?php if($this->form_data['send_payment_method']): ?>
            <tr>
                <td>
                    MethodID
                </td>
                <td>
                    <input type="text" name="MethodID" value="<?= $this->form_data['method_id'] ?>"/>
                </td>
            </tr>
            <?php endif; ?>

            <?php if($this->form_data['send_product_description']): ?>
            <?php if($this->form_data['product_description_ref']): ?>
                <tr>
                    <td>
                        Description
                    </td>
                    <td>
                        <input type="text" name="Description" value="<?= "Ref. no.: ".$this->form_data['order_id'] ?>"/>
                    </td>
                </tr>
                <?php else: ?>
                <tr>
                    <td>
                        Description
                    </td>
                    <td>
                        <input type="text" name="Description" value="<?= $this->form_data['product_description_custom'] ?>"/>
                    </td>
                </tr>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($this->form_data['skip_payment_page']): ?>
            <?php if(!in_array($this->form_data['method_id'], array(1, 20))): ?>
                <tr>
                    <td>
                        SkipHPP
                    </td>
                    <td>
                        <input type="text" name="SkipHPP" value="1"/>
                    </td>
                </tr>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($this->form_data['redirect_in_iframe']): ?>
            <tr>
                <td>
                    RedirectInIframe
                </td>
                <td>
                    <input type="text" name="RedirectInIframe" value="1"/>
                </td>
            </tr>
            <?php endif; ?>

            <?php if($this->form_data['skin_id']): ?>
            <tr>
                <td>
                    SkinID
                </td>
                <td>
                    <input type="text" name="SkinID" value="<?=$this->form_data['skin_id']?>"/>
                </td>
            </tr>
            <?php endif; ?>

            <tr>
                <td>
                    Hash
                </td>
                <td>
                    <input type="text" name="Hash" value="<?= $this->form_data['hash'] ?>"/>
                </td>
            </tr>
            <tr>
                <td colspan='2'>
                    <input type="submit" value="Submit"/>
                </td>
            </tr>
        </table>
    </form>
</div>

<div id="iframe-container" style="display: none; position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 1000">
    <div style="position: relative; width: 100%; height: 100%;">
        <div style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; background: #333; opacity: 0.5; filter:alpha(opacity=50)"></div>
        <div style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;">
            <div style="display: table; margin: 0px auto; margin-top: 50px;">
                <?php if($this->form_data['redirect_in_iframe'] && $this->form_data['skip_payment_page'] && ($this->form_data['method_id'] == 1001 || $this->form_data['method_id'] == 1002)):?>
				<iframe style='border: none; margin: 0px auto; background-color: #ffffff;' id="merchantIframe" name="merchantIframe" src="" width="780" height="500">
				<?php else:?>
				<iframe style='border: none; margin: 0px auto; background-color: transparent;' id="merchantIframe" name="merchantIframe" src="" width="900" height="800">
				<?php endif;?>
				
				</iframe>
            </div>
        </div>
    </div>
</div>

<script src="https://apitest.smart2pay.com/Scripts/jquery-1.7.2.min.js"></script>
<script>

    jQuery.noConflict();

    function modalIframe(){
        jQuery("#iframe-container").css({height: jQuery('body').height()});
        jQuery("#iframe-container").appendTo('body').show();
    }

    jQuery(document).ready(function() {

        jQuery('#s2pform').submit(function(){
            modalIframe();
        });
        // autosend form if needed
    <?php if(!$this->form_data['debug_form']): ?>
        jQuery("#s2pform").submit();
        <?php endif; ?>
        // get/parse smart2pay message
        var onmessage = function(e) {
            console.log(e);
            if(e.data == 'close_HPP') {
                setTimeout(function() {jQuery('iframe#merchantIframe').remove()}, 300);
            }
            else if (e.data.substring(0, 7) == "height=") {
                var iframe_height = e.data.substring(7);
                jQuery('iframe#merchantIframe').attr('height', parseInt(iframe_height)+300);
                console.log("jQuery('iframe#merchantIframe').attr('height'," + (parseInt(iframe_height)+300) + ");");
            }
            else if (e.data.substring(0, 6) == "width=") {
                var iframe_width = e.data.substring(6);
                jQuery('iframe#merchantIframe').attr('width', parseInt(iframe_width)+100);
                console.log("jQuery('iframe#merchantIframe').attr('width'," + (parseInt(iframe_width)+100) + ");");
            }

            else if  (e.data.substring(0, 12) == "redirectURL="){
                window.location = e.data.substring(12);
            }
        }
        // set event listener for smart2pay
        if(typeof window.addEventListener != 'undefined') {
            window.addEventListener('message', onmessage, false);
        }
        else if(typeof window.attachEvent != 'undefined') {
            window.attachEvent('onmessage', onmessage);
        }
    });
</script>